    
# Glitch-Community CircleCI Config
#
# Note: Version 2.1 is required in order to use orbs.
#
# Dependencies: Cypress.IO Orb

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
jobs:
  lint_and_build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: update-pnpm
          command: 'sudo npm install -g pnpm@latest'
      - run:
          name: pnpm-install
          command: pnpm install
      - run:
          name: eslint
          command: pnpm run lint
      - run:
          name: build
          command: pnpm run build
      - save_cache:
          key: build
          paths:
            - build
workflows:
  version: 2.1
  regular-workflow:
    jobs:
      - lint_and_build
      - cypress/install:
          requires:
            - lint_and_build
      - cypress/run:
          requires:
            - cypress/install
          start: npm run start
          wait-on: 'http://localhost:8000'
          store_artifacts: true
          record: true