    
# Glitch-Community CircleCI Config
#
# Note: Version 2.1 is required in order to use orbs.
#
# Dependencies: Cypress.IO Orb

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
jobs:
  lint:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/Glitch-Community
    steps:
      - checkout
      - run:
          name: update-pnpm
          command: 'sudo npm install -g pnpm@latest'
      - run:
          name: pnpm-install
          command: pnpm install
      - run:
          name: eslint
          command: pnpm run lint
workflows:
  version: 2.1
  regular-workflow:
    jobs:
      - lint
      - cypress/install:
          requires:
            - lint
      - cypress/run:
          requires:
            - cypress/install
          start: npm run ci:start
          wait-on: 'http://localhost:8000'
          store_artifacts: true
          record: true